#' Simulated Data for a Two Random Effects Model
#'
#' This dataset was generated to illustrate a random effects model with two random effects.
#' The response variable \code{y} is modeled as:
#'
#' \deqn{y = \beta_0 + u_{1[i]} + u_{2[j]} + \epsilon}
#'
#' where:
#' \itemize{
#'   \item \eqn{\beta_0} is the fixed intercept (set to 2).
#'   \item \eqn{u_{1[i]}} is the random effect for \code{groupA} (10 levels, \eqn{\sigma_{u1} = 1}).
#'   \item \eqn{u_{2[j]}} is the random effect for \code{groupB} (10 levels, \eqn{\sigma_{u2} = 1e-5}).
#'   \item \eqn{\epsilon} is the residual error (with \eqn{\sigma_e = 0.2}).
#' }
#'
#' The simulation sets:
#' \describe{
#'   \item{nA}{10 levels for \code{groupA}.}
#'   \item{nB}{10 levels for \code{groupB}.}
#'   \item{nRep}{10 replicates per combination of groups.}
#' }
#'
#' @details
#' The data is generated by:
#' \enumerate{
#'   \item Setting a fixed seed for reproducibility.
#'   \item Simulating the random effects for \code{groupA} and \code{groupB} using a normal distribution.
#'   \item Creating a data frame with all combinations of \code{groupA}, \code{groupB}, and replicates.
#'   \item Computing the response variable \code{y} by summing the fixed intercept, the corresponding random effects,
#'         and a normally distributed error term.
#' }
#'
#' @source Simulated data generated for demonstration purposes.
#'
#' @examples
#' # Load the dataset and display the first few rows:
#' data(example)
#' head(example)
#'
#' @name example
#' @docType data
"example"
